apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: llm-frontend
  template:
    metadata:
      labels:
        app: llm-frontend
    spec:
      containers:
        - name: llm-frontend
          image: ghcr.io/kieranarchi98/devops-ci-cd-automated-pipeline-frontend:latest
          ports:
            - containerPort: 80
